### ISSUE TITLE
Do't show layout in preview

### ISSUE THREAD

**Issue by tellfa** [mwolfson/android-historian#2]
tnx for this project, but i can't show layout in Preview tab. 
please see this image : http://uploads.im/CNgzu.jpg
i do rebuild and clean project, but not fix
how to fix it?

**Comment by mwolfson** [comment]
There is nothing wrong with the project - this is related to your local Android Studio configuration (update your tools, etc).  To be clear, I just opened the project locally, and was able to see the UI preview (so confirmed there is nothing specific to the project configuration causing issues). Preview image included as proof.

Bottom line, please update your tools, as your problem with seeing the preview is local to your environment, and not an issue with the project.

![screen shot 2015-09-06 at 6 50 54 am](https://cloud.githubusercontent.com/assets/295446/9704676/e4014428-5463-11e5-9d65-42029dead5f5.png)
