### ISSUE TITLE
FAB button go over toolbar

### ISSUE THREAD

**Issue by hishamBakr** [mwolfson/android-historian#4]
Thanks for great effort. However, I discovered an issue that when you scroll details screen, FAB button go over toolbar

**Comment by mwolfson** [comment]
This is not a bug, but is the nature of the CoordinatorLayout design.  Since the FAB is anchored to a view that scrolls out of view, the FAB follows this (and goes out of view as well).  This is super easy to change by anchoring to a different view using the _app:layout_anchor_ attribute
