### ISSUE TITLE
not really a problem

### ISSUE THREAD

**Issue by rubinbasha** [mwolfson/android-historian#6]
In UserActivity there is a bug if you just click the save button.

String formattedNum = PhoneNumberUtils.stripSeparators(phoneEnterField.getText().toString());
                final long phoneToSet = Long.valueOf(formattedNum);

// the problem is that it cant convert "" to a number
If I leave the phone number empty and also the nickname, than click save and it crashes. This is not a big problem, just wanted to give the feedback.

Thank you for implementing so many things in this project.
Rubin Basha

**Comment by mwolfson** [comment]
Thanks, hate for stuff to crash, so will fix.
