### ISSUE TITLE
PullToRefreshView not working

### ISSUE THREAD

**Issue by hemant4524** [mwolfson/android-historian#7]
<?xml version="1.0" encoding="utf-8"?>
<com.yalantis.phoenix.PullToRefreshView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/pull_to_refresh"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerview"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</com.yalantis.phoenix.PullToRefreshView>

https://github.com/Yalantis/Phoenix

I am try to implement pull to refresh in this example  not working.

**Comment by mwolfson** [comment]
This has nothing to do with this repo, and is NOT an issue (PULL to refresh is not a part of the example in the first place).  Also, you opened a issue with the other repo too (again, not that repos problem that you can't get your code working).  
Please use Github issues to address bugs with the existing implementation, and not to address issues with your extension of the project (again, this is NOT an issue with this project).
Perhaps you should try Stackoverflow for your issues.

**Comment by hemant4524** [comment]
It's my mistake. This project working fine.
