### ISSUE TITLE
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by MarioGallegos** [mwolfson/android-historian#9]
When I try to use the gradlew.

**Comment by MarioGallegos** [comment]
When I try to use gradlew.

**Comment by mwolfson** [comment]
Good luck, this is not a bug with the repo, but a problem with your environment
http://stackoverflow.com/questions/29805622/could-not-find-or-load-main-class-org-gradle-wrapper-gradlewrappermain

**Comment by nagababu27** [comment]
i have solved this error by changing name of the folder
